name: "Reuse Action"
inputs:
  branch:
    required: true

runs:
  using: "composite"
  steps:
    - name: First statement
      run: |
        echo "This is the first"
        echo ${{ inputs.branch }}
      shell: bash