name: Deploy reusable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy first part (composite)
        uses: mmcglynnbraingu/test-workflow-reuse/.github/actions/reuse
      - name: Second part
        run: echo "This is second"
