name: Deploy

on:
  #required for a reusable workflow
  workflow_call:
    inputs:
      envName:
        description: "The environment to deploy to"
        required: true
        default: "sandbox"
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.envName }}
    steps:
      - uses: actions/checkout@v2
      - name: set environment variables
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=${GIT_BRANCH}" >> ${GITHUB_ENV}
      - name: Deploy first part (composite)
        uses: mmcglynnbraingu/test-workflow-reuse/.github/actions/reuse@main
        with:
          branch: replace($GIT_BRANCH, '/', '-')
      - name: Second part
        run: echo replace($GIT_BRANCH, '/', '-')

  sayMessage:
    runs-on: ubuntu-latest
    environment: ${{ inputs.envName }}
    steps:
      - uses: actions/checkout@v2
      - name: End of job
        run: echo "The deployment to this environment has finished"
