name: Deploy reusable

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Reusable part
        uses: mmcglynnbraingu/test-workflow-reuse/.github/workflows/reuse.yml@main
      - name: Second part
        run: echo "This is second"
