name: Reuse

on:
  workflow_call:

jobs:
  reuse:
    name: Echo statement to be reused
    steps:
      - uses: actions/checkout@v2
      - name: First statement
        run: echo "This is the first"
