name: Reusable Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'  #A README.md file anywhere in the repository
      - '**/docs/**'        #Any files in the /docs directory at the root of the repository
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'  #A README.md file anywhere in the repository
      - '**/docs/**'        #Any files in the /docs directory at the root of the repository

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: 'Where to release? (Current option is sandbox)'
        required: true
        default: 'sandbox'
        options:
          - sandbox
          - test
          - govTest
          - prod
          - govProd

jobs:
  sandbox:
    uses: mmcglynnbraingu/test-workflow-reuse/.github/workflows/deploy.yml@main
    with:
      envName: "sandbox"
  
  test:
    if: github.event.inputs.releaseType == 'test'
    needs: sandbox
    uses: mmcglynnbraingu/test-workflow-reuse/.github/workflows/deploy.yml@main
    with:
      envName: "test"

  govTest:
    if: github.event.inputs.releaseType == 'govTest'
    needs: sandbox
    uses: mmcglynnbraingu/test-workflow-reuse/.github/workflows/deploy.yml@main
    with:
      envName: "govTest"

  prod:
    if: github.event.inputs.releaseType == 'prod' || github.events.inputs.releaseType == 'test'
    needs: test
    uses: mmcglynnbraingu/test-workflow-reuse/.github/workflows/deploy.yml@main
    with:
      envName: "prod"

  govProd:
    if: github.event.inputs.releaseType == 'govProd' || github.events.inputs.releaseType == 'govTest'
    needs: govTest
    uses: mmcglynnbraingu/test-workflow-reuse/.github/workflows/deploy.yml@main
    with:
      envName: "govProd"