name: Reusable Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'  #A README.md file anywhere in the repository
      - '**/docs/**'        #Any files in the /docs directory at the root of the repository
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'  #A README.md file anywhere in the repository
      - '**/docs/**'        #Any files in the /docs directory at the root of the repository

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: 'Where to release? (Current option is sandbox)'
        required: true
        default: 'sandbox'
        options:
          - sandbox
          - test
          - govTest
          - prod
          - govProd

jobs:
  sandbox:
    if: github.event_name == 'pull_request'
    uses: mmcglynnbraingu/test-workflow-reuse/.github/actions/workflow/deploy.yml
    with:
      envName: "sandbox"
  
  test:
    if: github.event.ref == 'refs/heads/main'
    needs: sandbox
    uses: mmcglynnbraingu/test-workflow-reuse/.github/actions/workflow/deploy.yml
    with:
      envName: "test"

  govTest:
    if: github.event.ref == 'refs/heads/main'
    needs: sandbox
    uses: mmcglynnbraingu/test-workflow-reuse/.github/actions/workflow/deploy.yml
    with:
      envName: "govTest"

  prod:
    needs: test
    uses: mmcglynnbraingu/test-workflow-reuse/.github/actions/workflow/deploy.yml
    with:
      envName: "prod"

  govProd:
    needs: govTest
    uses: mmcglynnbraingu/test-workflow-reuse/.github/actions/workflow/deploy.yml
    with:
      envName: "govProd"